# 02 - Data Cleaning

## Online Retail Sales & Customer Analysis

This notebook prepares the raw transaction data for exploratory and customer-level analysis.

Cleaning decisions are based on the project's analytical objectives and the findings identified during the data-understanding stage. Rather than automatically removing unusual values, each cleaning step is applied according to the meaning and intended use of the data.

In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("../OnlineRetail.xlsx")

In [4]:
df.shape

(541909, 8)

In [5]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

### 1. Negative Quantities

Negative quantities are retained in the cleaned dataset because they may represent cancellations, returns, or other negative transactions. Removing them would prevent these transactions from reducing the corresponding positive sales and could therefore distort net revenue calculations.

The exact business meaning of each negative transaction will be considered when performing specific analyses. For example, negative transactions may need to be treated differently when analyzing purchasing frequency or customer behaviour than when calculating net revenue.

In [7]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [8]:
df["Revenue"].describe()

count    541909.000000
mean         17.987795
std         378.810824
min     -168469.600000
25%           3.400000
50%           9.750000
75%          17.400000
max      168469.600000
Name: Revenue, dtype: float64

In [9]:
df.nlargest(10,"Revenue")[["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID", "Revenue"]]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Revenue
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446.0,168469.60
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346.0,77183.60
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,15098.0,38970.00
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,NaN,13541.33
299982,A563185,B,Adjust bad debt,1,11062.06,NaN,11062.06
173382,551697,POST,POSTAGE,1,8142.75,16029.0,8142.75
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,17450.0,7144.72
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,6539.40
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,6539.40
421601,573003,23084,RABBIT NIGHT LIGHT,2400,2.08,14646.0,4992.00

In [10]:
df.nsmallest(10, "Revenue")[["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID", "Revenue"]]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Revenue
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2.08,16446.0,-168469.60
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1.04,12346.0,-77183.60
222681,C556445,M,Manual,-1,38970.00,15098.0,-38970.00
524602,C580605,AMAZONFEE,AMAZON FEE,-1,17836.46,NaN,-17836.46
43702,C540117,AMAZONFEE,AMAZON FEE,-1,16888.02,NaN,-16888.02
43703,C540118,AMAZONFEE,AMAZON FEE,-1,16453.71,NaN,-16453.71
15016,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,-13541.33
16356,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,-13541.33
16232,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,NaN,-13474.79
524601,C580604,AMAZONFEE,AMAZON FEE,-1,11586.50,NaN,-11586.50